"""Optional LLM explanation layer for skill-gap analysis.

Never replaces the grounded analysis — it only rewrites it into a
human-friendly coaching narrative. Falls back to a template explanation
if Ollama is unavailable or returns unusable JSON.
"""
from __future__ import annotations

import json
import logging
import re
from typing import Dict, List

from app.features.job_recommendation.config import OLLAMA_BASE_URL, OLLAMA_MODEL

logger = logging.getLogger(__name__)

EXPLANATION_PROMPT = """
You are a warm, specific career coach. Rewrite the grounded skill-gap
analysis below into advice a candidate would actually want to read.

Hard rules:
- Use ONLY skills, job titles, companies, and numbers from the input.
- Never invent a missing skill. If a job's missing_skills list is empty,
  that candidate already matches the role — congratulate them and tell
  them to apply. Do not borrow gaps from other jobs.
- Copy each job title EXACTLY as given.
- strategic_learning_sequence may only contain skill names that appear
  in learning_path. Reorder them if a smarter sequence is obvious.
- If the candidate's name is present, address them by first name once.
- Write like a human: varied sentences, concrete, encouraging, no filler
  like "crucial/essential/fundamental skill for many roles".
- Do not mention that this was computed, rule-based, or generated by a model.

Output ONLY valid JSON with these keys:
{
  "headline": "short punchy line (max 12 words)",
  "summary": "2-4 sentences of coaching. Name the biggest opportunity and why.",
  "job_advice": [
    {"title": "<exact title from input>", "advice": "2-3 sentences for THIS job only"}
  ],
  "strategic_learning_sequence": ["skill names from learning_path"],
  "closing": "one encouraging next step in a single sentence"
}
Include one job_advice object for EVERY job in the input, in the same order.
""".strip()


def _resume_excerpt(preprocessed: dict) -> str:
    text = str((preprocessed or {}).get("raw_text") or "").strip()
    if not text:
        sections = (preprocessed or {}).get("sections") or {}
        parts = [str(v) for v in sections.values() if v]
        text = "\n".join(parts)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:1800]


def attach_candidate_context(grounded: dict, preprocessed: dict) -> dict:
    entities = (preprocessed or {}).get("entities") or {}
    grounded["candidate"] = {
        "name": entities.get("name") or "",
        "years_exp": entities.get("years_exp") or "",
        "location": entities.get("location") or "",
    }
    grounded["resume_excerpt"] = _resume_excerpt(preprocessed)
    return grounded


def _build_llm_payload(grounded: dict) -> dict:
    candidate = grounded.get("candidate") or {}
    return {
        "candidate": candidate,
        "resume_excerpt": grounded.get("resume_excerpt") or "",
        "current_skills": grounded.get("resume_skills", [])[:40],
        "jobs": [
            {
                "title": j["title"],
                "company": j["company"],
                "matching_skills": j["matching_skills"],
                "missing_skills": j["missing_skills"],
                "match_ratio": j.get("match_ratio"),
            }
            for j in grounded.get("job_breakdown", [])
        ],
        "learning_path": [
            {
                "skill": s["skill"],
                "category": s["category"],
                "blocks_roles": s["blocks_roles"],
                "readiness": s["readiness"],
                "note": s.get("note") or "",
            }
            for s in grounded.get("learning_path", [])
        ],
        "closest_roles": [
            {"title": j["title"], "company": j["company"], "match_ratio": j["match_ratio"]}
            for j in grounded.get("closest_roles", [])
        ],
        "repeated_gaps": grounded.get("repeated_gaps", []),
        "focus_track": grounded.get("focus_track"),
    }


def _job_advice_for(job: dict) -> dict:
    missing = job.get("missing_skills") or []
    matching = job.get("matching_skills") or []
    title = job["title"]
    company = job.get("company") or ""
    where = f" at {company}" if company else ""
    if not missing:
        strengths = ", ".join(matching[:4]) or "the skills this role lists"
        return {
            "title": title,
            "advice": (
                f"You're already a strong match for {title}{where}. "
                f"Your resume already covers {strengths}. Apply now and lead with those skills."
            ),
        }
    lead = missing[0]
    rest = missing[1:]
    have = f" You already bring {', '.join(matching[:3])}." if matching else ""
    extra = (
        f" After that, add {', '.join(rest)} to round out the profile."
        if rest
        else ""
    )
    return {
        "title": title,
        "advice": (
            f"For {title}{where}, start with {lead} — it's the gap that will move the needle fastest."
            f"{have}{extra}"
        ),
    }


def _fallback_explanation(grounded: dict) -> Dict:
    focus = grounded.get("focus_track")
    gaps = grounded.get("repeated_gaps") or []
    closest = grounded.get("closest_roles") or []
    candidate = grounded.get("candidate") or {}
    first = (candidate.get("name") or "").split()[0] if candidate.get("name") else ""
    hello = f"{first}, " if first else ""

    summary_parts: List[str] = []
    if closest:
        top = closest[0]
        pct = round((top.get("match_ratio") or 0) * 100)
        summary_parts.append(
            f"{hello}your closest fit is {top['title']}"
            + (f" at {top['company']}" if top.get("company") else "")
            + f" ({pct}% skill match)."
        )
    if focus:
        summary_parts.append(
            f"The biggest shared gap across these roles is {focus['category']}: {focus['reason']}"
        )
    if gaps:
        top_gap = gaps[0]
        summary_parts.append(
            f"If you only pick one skill to start, make it {top_gap['skill']} — "
            f"it shows up in {top_gap['blocks_roles']} of these roles."
        )
    sequence = [step["skill"] for step in grounded.get("learning_path", [])]
    return {
        "headline": (
            f"Close {gaps[0]['skill']} first" if gaps else "You're closer than you think"
        ),
        "summary": " ".join(summary_parts)
        or "No major skill gaps were found across your top recommendations.",
        "job_advice": [_job_advice_for(j) for j in grounded.get("job_breakdown", [])],
        "strategic_learning_sequence": sequence,
        "closing": (
            f"Start with {sequence[0]} this week and you'll be a clearer match for more of these roles."
            if sequence
            else "You're ready to apply to the closest-matching roles on this list."
        ),
        "used_llm": False,
        "backend": "grounded-fallback",
    }


def _normalize_advice_list(raw_advice, jobs: List[dict]) -> List[dict]:
    by_title = {}
    for item in raw_advice or []:
        if not isinstance(item, dict):
            continue
        title = str(item.get("title") or "").strip()
        advice = str(item.get("advice") or "").strip()
        if title and advice:
            by_title[title.lower()] = {"title": title, "advice": advice}

    ordered = []
    for idx, job in enumerate(jobs):
        key = (job.get("title") or "").lower()
        llm_item = by_title.get(key)
        missing = job.get("missing_skills") or []
        if llm_item:
            invented_gap = (not missing) and re.search(
                r"\b(missing|lack|don't have|do not have|need to learn)\b",
                llm_item["advice"],
                re.I,
            )
            if invented_gap:
                ordered.append(_job_advice_for(job))
            else:
                ordered.append({"title": job["title"], "advice": llm_item["advice"]})
        elif isinstance(raw_advice, list) and idx < len(raw_advice) and isinstance(raw_advice[idx], dict):
            advice = str(raw_advice[idx].get("advice") or "").strip()
            ordered.append({"title": job["title"], "advice": advice} if advice else _job_advice_for(job))
        else:
            ordered.append(_job_advice_for(job))
    return ordered


def _sanitize_explanation(result: dict, grounded: dict, used_llm: bool, backend: str) -> Dict:
    jobs = grounded.get("job_breakdown") or []
    path_skills = [step["skill"] for step in grounded.get("learning_path") or []]
    path_set = {s.lower(): s for s in path_skills}

    fallback = _fallback_explanation(grounded)
    summary = str(result.get("summary") or "").strip() or fallback["summary"]
    headline = str(result.get("headline") or "").strip() or fallback["headline"]
    closing = str(result.get("closing") or "").strip() or fallback["closing"]

    sequence_raw = result.get("strategic_learning_sequence") or []
    sequence = []
    seen = set()
    for skill in sequence_raw:
        name = path_set.get(str(skill).strip().lower())
        if name and name not in seen:
            sequence.append(name)
            seen.add(name)
    for skill in path_skills:
        if skill not in seen:
            sequence.append(skill)
            seen.add(skill)

    return {
        "headline": headline[:80],
        "summary": summary,
        "job_advice": _normalize_advice_list(result.get("job_advice"), jobs),
        "strategic_learning_sequence": sequence,
        "closing": closing,
        "used_llm": used_llm,
        "backend": backend,
    }


def _call_ollama_json(prompt: str, model: str = OLLAMA_MODEL) -> Dict:
    import requests

    url = f"{OLLAMA_BASE_URL.rstrip('/')}/api/chat"
    payload = {
        "model": model or OLLAMA_MODEL,
        "stream": False,
        "format": "json",
        "options": {"temperature": 0.45},
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are a career coach. Return only valid JSON. "
                    "Never invent skills, job titles, or numbers."
                ),
            },
            {"role": "user", "content": prompt},
        ],
    }
    resp = requests.post(url, json=payload, timeout=120)
    resp.raise_for_status()
    text = (resp.json().get("message", {}).get("content", "") or "").strip()
    if text.startswith("```json"):
        text = text[len("```json"):].strip()
    elif text.startswith("```"):
        text = text[3:].strip()
    if text.endswith("```"):
        text = text[:-3].strip()

    start = text.find("{")
    if start == -1:
        raise RuntimeError("Ollama did not return any JSON object.")

    decoder = json.JSONDecoder()
    data, _ = decoder.raw_decode(text[start:])
    if not isinstance(data, dict):
        raise RuntimeError("Ollama did not return a JSON object.")
    data["_llm_backend"] = "ollama"
    data["_llm_model"] = model or OLLAMA_MODEL
    return data


def explain_with_llm(grounded: dict, model: str = OLLAMA_MODEL) -> Dict:
    payload = _build_llm_payload(grounded)
    prompt = (
        f"{EXPLANATION_PROMPT}\n\nGrounded analysis JSON:\n"
        f"{json.dumps(payload, ensure_ascii=False, indent=2)}"
    )
    try:
        result = _call_ollama_json(prompt, model)
        summary = result.get("summary") or ""
        job_advice = result.get("job_advice") or []
        sequence = result.get("strategic_learning_sequence") or []
        if not summary and not job_advice and not sequence:
            raise RuntimeError(f"Ollama returned JSON with no usable fields: {result!r}")
        return _sanitize_explanation(
            result,
            grounded,
            used_llm=True,
            backend=result.get("_llm_backend") or "ollama",
        )
    except Exception as exc:
        logger.warning("Ollama explanation unavailable (%s); using grounded fallback", exc)
        return _fallback_explanation(grounded)
